import type { Metadata } from "next";
import { ProfileSidebar } from "@/components/profile-sidebar";

export const metadata: Metadata = {
  title: "Tesk Task | Profile",
  description: "Generated by create next app",
};

export default function ProfileLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      {children}
      <ProfileSidebar />
    </>
  );
}
